### PR TITLE
fix: Add "default" export conditions for `browser` and `node` platforms when applicable.

### PR DESCRIPTION
**Pull request by milesj**
Noticed some issues with our exports, specifically with Jest v28, is that `jest-environment-jsdom` does not resolve our `browser` condition and throws a "Cannot find module" error.

By default, jest only considers the `browser` condition (which contains `import`/`module`) (https://jestjs.io/docs/configuration#testenvironmentoptions-object) and does not match against the outer `node` or `default`. 

```diff
"exports": {
  "./package.json": "./package.json",
  ".": {
    "types": "./dts/index.d.ts",
    "browser": {
      "module": "./esm/index.js",
      "import": "./esm/index.js",
+     "default": "./lib/index.js"
    },
    "node": {
      "import": "./cjs/index-wrapper.mjs",
      "require": "./cjs/index.cjs",
+     "default": "./lib/index.js"
    },
    "default": "./lib/index.js"
  }
}
```

Because of this, our exports are basically ESM only, but jest does not support ESM that well yet. I'm trying to figure out the best way to handle this... I think the only solution is to add `default` to each condition again (above).

### CODE REVIEW

**Comment by milesj** [comment]
Hey @azu, since you've been using Packemon a bit lately, curious if you've run into this problem yet.

**Comment by azu** [comment]
I have not met this issue yet.

I did a quick search, I could not found thie `default` issue
https://github.com/facebook/jest/issues/9771
https://github.com/facebook/jest/blob/05469328f49bd1d2435c47a70c47983355bc4f54/packages/jest-resolve/src/defaultResolver.ts#L11-L14
https://github.com/lukeed/resolve.exports#readme

@dai-shi written an atritcle about conditional exports. He may know somthing about this issue.
[How Jotai Specifies Package Entry Points · Daishi Kato's blog](https://blog.axlight.com/posts/how-jotai-specifies-package-entry-points/)

**Comment by dai-shi** [comment]
tbh, we are still having issues with jest. ex. https://github.com/dai-shi/proxy-memoize/issues/42#issuecomment-1110495594

> I think the only solution is to add `default` to each condition again (above).

If adding `default` solves it, I think it's a good solution.

**Comment by milesj** [comment]
@dai-shi Yeah, I think to unblock for now, I'll add the default. I think in v3 I'll revisit the exports a bit and improve them if applicable.

**Pull request merged**
